/**
 * API integration testing
 * Simplified version: Verify that the module can be loaded and the basic structure is correct
 */

const vm = require('vm');

/**
 * Extract all <script> blocks from HTML and verify that the JS syntax is legal
 * Use vm.Script to do static syntax checking without actually executing the code
 */
function assertScriptSyntax(html, label) {
  const scriptRegex = /<script>([\s\S]*?)<\/script>/g;
  let match;
  let count = 0;
  while ((match = scriptRegex.exec(html)) !== null) {
    count++;
    const src = match[1];
    // Use try/catch instead of .not.toThrow(string) - the string parameter of the latter is a pattern that matches the error message that is thrown.
    // Not a custom failure description. If the SyntaxError message does not contain this string, the test may fail and lose the value of regression protection.
    try {
      new vm.Script(src);
    } catch (e) {
      throw new Error(
        `${label} The ${count}th <script> block JS syntax error: ${e.message}\\nBegins:\\n${src.slice(0, 200)}`
      );
    }
  }
  // Make sure that the script block is actually found (to prevent regex from being written incorrectly and causing empty running)
  expect(count).toBeGreaterThan(0);
}

// ── Regression testing: The script block generated by the server-side template must not have JS syntax errors ─────────────
// The root cause of this bug: single quotes in translated text break the inline JS string syntax.
// This can be avoided entirely by escaping with JSON.stringify(). The English interface is the easiest to trigger (containing abbreviations such as can't).
describe('HTML embedded script block syntax legality (regression defense)', () => {
  let mod;

  beforeAll(() => {
    // Set NODE_ENV=test to get test-specific exports
    process.env.NODE_ENV = 'test';
    // Clear require cache and make sure to reload in test mode
    delete require.cache[require.resolve('./adminServer')];
    mod = require('./adminServer');
  });

  test('receiptsPage - English interface script block has no syntax error', () => {
    const html = mod._receiptsPage([], 'en');
    assertScriptSyntax(html, 'receiptsPage(en)');
  });

  test('receiptsPage - English interface script block has no grammatical errors', () => {
    const html = mod._receiptsPage([], 'en');
    assertScriptSyntax(html, 'receiptsPage(en)');
  });

  test('usersPage - English interface script block has no syntax error', () => {
    const html = mod._usersPage([], 'admin', '', 'en');
    assertScriptSyntax(html, 'usersPage(en)');
  });

  test('usersPage - English interface script block has no grammatical errors', () => {
    const html = mod._usersPage([], 'admin', '', 'en');
    assertScriptSyntax(html, 'usersPage(en)');
  });

  test('qrPage - English interface script block has no syntax errors', () => {
    const html = mod._qrPage('en');
    assertScriptSyntax(html, 'qrPage(en)');
  });

  test('qrPage - English interface script block has no grammatical errors', () => {
    const html = mod._qrPage('en');
    assertScriptSyntax(html, 'qrPage(en)');
  });
});

// Verification module can be imported
describe('module loading', () => {
  test('adminServer can be imported', () => {
    expect(() => {
      require('./adminServer');
    }).not.toThrow();
  });

  test('Export the correct interface', () => {
    const mod = require('./adminServer');
    expect(mod).toHaveProperty('startAdminServer');
    expect(mod).toHaveProperty('setClient');
    expect(mod).toHaveProperty('setQR');
    expect(mod).toHaveProperty('setPairingCodeReady');
    expect(typeof mod.startAdminServer).toBe('function');
  });
});

// Verify that key module dependencies can be imported
describe('Dependent modules', () => {
  test('sessionManager can be imported', () => {
    const mod = require('./sessionManager');
    expect(mod).toHaveProperty('SESSION_STATE');
    expect(mod).toHaveProperty('getOrCreateSession');
  });

  test('excelService can be imported', () => {
    const mod = require('./services/excelService');
    expect(mod).toBeDefined();
    expect(mod).toHaveProperty('getExcelPath');
  });

  test('icParser can be imported', () => {
    const { validateIC } = require('./utils/icParser');
    expect(typeof validateIC).toBe('function');
  });

  test('maskPhone can be imported', () => {
    const { maskPhone } = require('./utils/maskPhone');
    expect(typeof maskPhone).toBe('function');
  });
});

// Verify configuration can be loaded
describe('Configuration loading', () => {
  test('config.yaml parsable', () => {
    const fs = require('fs');
    const yaml = require('js-yaml');
    const path = require('path');

    const configPath = path.join(__dirname, '../../config/config.yaml');
    const config = yaml.load(fs.readFileSync(configPath, 'utf8'));

    expect(config).toHaveProperty('bot');
    expect(config.bot).toHaveProperty('session_timeout_minutes');
    expect(config.bot).toHaveProperty('max_receipts_per_day');
  });
});
